### ISSUE TITLE
Add license to all the code :)

### ISSUE THREAD

**Issue by sethladd** [stevenroose/watch-with-me#4]
I see a lot of code that doesn't have a license. Just FYI, might want to add a license to everything.

Thanks!

**Comment by sethladd** [comment]
Basically:
- Add a license at the top of every source file
- Add a LICENSE file to the project itself

IANAL but this is a good first step

**Comment by stevenroose** [comment]
I know that's how it should be and I've been planning to do that for all
the projects I have on GitHub.

But I'm generally not very worried about my code, I just add the MIT
license when I initialize a repo, but I think IntelliJ has an automatic
function to add preambles. Should check that out.

**Comment by sethladd** [comment]
Without a license, it makes it hard for us to point to.

**Comment by sethladd** [comment]
Thanks!
